Repository codemaniac-sahil/random_jokes, pull requests merged in 2022-10, with the labels that each got.

#11 Added social media buttons
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#15 aligned socials
  index.html
  style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#23 Added copyright
  index.html
  script.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#24 Changed the font style of the heading
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#26 Responsive webpage
  .vscode/settings.json
  style.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#27 added comments defining media queries
  style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#30 Added An Icon For Discord
  index.html
  script.js
  style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#31 Added option to share on whatsapp
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#33 Improved Responsiveness
  index.html
  style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
